### ISSUE TITLE
Loading checkpoint None Error - FIx please

### ISSUE THREAD

**Issue by srikanthNDM** [DanTm99/gpt2-article-generator#2]
Getting error:
` None
Loading checkpoint None
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\gpt2-article-generator-master\gpt2handler.py", line 65, in load_model
    gpt2.load_gpt2(self.sess, run_name=self.run_name)
  File "C:\Users\Sree\AppData\Local\Programs\Python\Python37\lib\site-packages\gpt_2_simple\gpt_2.py", line 399, in load_gpt2
    saver.restore(sess, ckpt)
  File "C:\Users\Sree\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sree\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "D:\gpt2-article-generator-master\gui.py", line 139, in submit
    words_per_sample)
  File "D:\gpt2-article-generator-master\generator.py", line 33, in generate_as_tuple
    return Gpt2Handler.get_instance().generate_as_tuple(title, initial_content, num_samples, num_words)
  File "D:\gpt2-article-generator-master\gpt2handler.py", line 41, in get_instance
    cls()
  File "D:\gpt2-article-generator-master\gpt2handler.py", line 55, in __init__
    self.load_model()
  File "D:\gpt2-article-generator-master\gpt2handler.py", line 68, in load_model
    gpt2.load_gpt2(sess, run_name=self.run_name)
  File "C:\Users\Sree\AppData\Local\Programs\Python\Python37\lib\site-packages\gpt_2_simple\gpt_2.py", line 399, in load_gpt2
    saver.restore(sess, ckpt)
  File "C:\Users\Sree\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\training\saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
`

**Comment by DanTm99** [comment]
What did you do to cause this error to appear?

**Comment by neliobnjr** [comment]
Hey guys I got this error:
Exception: Model is missing. Place '124M_article_generator_model' in the checkpoint folder and try again.

**Comment by DanTm99** [comment]
> Hey guys I got this error:
> Exception: Model is missing. Place '124M_article_generator_model' in the checkpoint folder and try again.

You can download the model from the Google Drive link in the readme.

**Comment by Sba-Stuff** [comment]
I downloaded model from Google drive. Yet it tries to download from internet why???? I don't have good internet home, i downloaded from internet cafe. Did you hardcoded paths? 
![image](https://user-images.githubusercontent.com/36412543/99079376-af121800-25e1-11eb-87f4-6023ea7a4718.png)

![image](https://user-images.githubusercontent.com/36412543/99079418-bc2f0700-25e1-11eb-9b37-fcc7145386db.png)

![image](https://user-images.githubusercontent.com/36412543/99079438-c5b86f00-25e1-11eb-9c7c-ee856fad2329.png)

Tried everything, didn't worked.

**Comment by DanTm99** [comment]
> I downloaded model from Google drive. Yet it tries to download from internet why???? I don't have good internet home, i downloaded from internet cafe. Did you hardcoded paths?
> ![image](https://user-images.githubusercontent.com/36412543/99079376-af121800-25e1-11eb-87f4-6023ea7a4718.png)
> 
> ![image](https://user-images.githubusercontent.com/36412543/99079418-bc2f0700-25e1-11eb-9b37-fcc7145386db.png)
> 
> ![image](https://user-images.githubusercontent.com/36412543/99079438-c5b86f00-25e1-11eb-9c7c-ee856fad2329.png)
> 
> Tried everything, didn't worked.

The model downloaded from Google Drive is a custom model that has been specialised for the use of this program. The model that is downloaded automatically is the base model, and is still required when using the custom model to generate text.

**Comment by DanTm99** [comment]
> I downloaded model from Google drive. Yet it tries to download from internet why???? I don't have good internet home, i downloaded from internet cafe. Did you hardcoded paths?

The model downloaded from Google Drive is a custom model that has been specialised for the use of this program. The model that is downloaded automatically is the base model, and is still required when using the custom model to generate text.

**Comment by Sba-Stuff** [comment]
Please add this in ReadMe.MD, to clarify to others. Thanks.
